version: '2'
services:
 magicscrape:
  image: magicplatform/magicscrape
  container_name: magicscrape
  #ports:
  # - "142.54.186.58:80:80"
  # - "142.54.186.58:443:443"
  environment:
   - TZ=PST8PDT
  restart: always
  networks:
   - proxy
  links:
   - redis

 magicapi:
  image: magicplatform/magicapi
  container_name: magicapi
  ports:
    - "172.31.30.131:8888:8888"
  environment:
   - TZ=PST8PDT
  restart: always
  networks:
   - proxy
  links:
   - redis

 redis:
  image: redis
  container_name: redis
  ports:
   - "172.31.30.131:6379:6379"
  environment:
   - TZ=PST8PDT
  restart: always
#  volumes:
  networks:
   - proxy

networks:
   proxy:
    external:
      name: icecrown
