version: '2'
services:
 magicapi:
  image: magicplatform/magicapi
  container_name: magicapi
  ports:
   - "192.168.1.1:8888:8888"
  # - "142.54.186.58:443:443"
  environment:
    - TZ=PST8PDT
  restart: always
  networks:
   - proxy
  external_links:
     - redis

networks:
   proxy:
    external:
      name: icecrown
