version: '2'
services:
 redis:
  image: magicplatform/redis
  container_name: redis
  ports:
   - "192.168.1.1:6379:6379"
  environment:
    - TZ=PST8PDT
  restart: always
#  volumes:
  networks:
   - proxy

networks:
   proxy:
    external:
      name: icecrown
